<a href="https://www.kaggle.com/code/khanbabaahamaliiev/pytorch-prac?scriptVersionId=356155665" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

Імпорт модулів

In [1]:
import torch

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [2]:
print(torch.cuda.is_available())  # True/False

if torch.cuda.is_available():
    print(torch.cuda.device_count())  # Кількість GPU
    print(torch.cuda.get_device_name(0))  # Назва першого GPU

tensor = torch.tensor([1, 2, 3])
print(tensor.device)  # CPU

True
2
Tesla T4
cpu


# Завдання 2
Підключіться до процесора GPU, та знову виведіть інформацію про доступні процесори

# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [3]:
tensor = torch.randn(2,3)
tensor
print(tensor.type())
print(tensor.device)
print(tensor.dtype)
print(tensor.shape)

torch.FloatTensor
cpu
torch.float32
torch.Size([2, 3])


# Завдання 4

Створіть 2 тензора розміру 100. Виведіть
* суму векторів
* частку векторів(перед цим замініть один елемент на 0)
* максимальне та мінімальне значення(методи .min() .max())
* середнє значення(метод .mean())
* квадрад різниці
* середнє значення квадрату різниці

In [4]:
tensor1 = torch.randn(100)
tensor2 = torch.randn(100)

tensor_sum = tensor1 + tensor2
print(tensor_sum)
print(tensor_sum.min())
print(tensor_sum.max())
print(tensor_sum.mean())

tensor_sub = tensor1 - tensor2
tensor_sqr = tensor_sub ** 2
print (tensor_sqr)

tensor_diff = tensor_sum / 2
print(tensor_diff)

print(tensor_sqr.mean())

tensor([ 0.1582,  0.8317,  0.2189,  1.4255, -0.9003, -1.5732,  1.0528,  1.4914,
        -0.9463, -2.7390,  3.0266,  3.2389, -0.0733, -1.5496,  0.4365,  0.6673,
        -0.8174,  0.4284, -1.0323,  0.5053, -1.9392,  1.2350, -0.7671, -0.6403,
         0.4592, -1.7055, -1.9563, -3.8560,  1.6064,  2.4109, -0.5678, -0.9564,
        -1.8257, -0.5701, -0.9855, -0.5673, -1.2309, -2.4139, -0.8255,  0.5291,
         0.1128, -0.3144, -2.0354,  0.4091,  1.1040,  0.7993, -1.3609,  0.0076,
        -0.2272, -0.5162,  0.3554,  0.9942,  1.1456,  0.0890,  0.8407, -0.8270,
         2.7321,  1.1676, -0.7413, -0.2486, -0.4892,  0.1912, -1.6054, -1.4504,
         0.7716, -4.1814, -1.3574,  1.2416,  1.9252, -1.7437,  0.9427, -0.3184,
         0.9515,  0.7693,  1.5189,  2.6268, -1.0875,  3.0534, -1.1998,  0.2864,
        -1.3635,  1.4220,  1.2560, -2.1591, -1.3102, -0.8458, -0.7716, -0.0259,
         1.0366,  2.5601,  0.8013, -1.2775,  0.4965,  0.4626, -2.9331,  2.0636,
         0.5172,  0.9606,  2.3209, -0.62

# Завдання 5

У вашому розпорядженні є нейронна мережа, яка прогнозує **орієнтовну ціну квартири** на основі двох **ознак**:

* **площі квартири** (у квадратних метрах);
* **кількості кімнат**.

Вам надано готовий клас `NeuralNetwork` із методом `predict`.

1. Створіть екземпляр класу `NeuralNetwork`, передайте як параметр `device`.
2. За допомогою методу `predict()` визначте прогнозовану ціну квартири, яка:
   * має площу **65 м²**;
   * має **2 кімнати**.
     
3. Для цього створіть тензор із відповідними числами та скористайтесь методом `predict()`.
4. Усі нейромережі очікують дані розміру `(N, K)`, де:
   * `N` — кількість об'єктів, для яких виконується прогноз;
   * `K` — кількість ознак. У цьому випадку їх дві — **площа квартири та кількість кімнат**.

5. Спробуйте скористатись методом `predict()` разом із `torch.no_grad()`:

```python
with torch.no_grad():
    price = model.predict(...)
```

**Завдання:** отримайте прогнозовану ціну квартири та виведіть результат на екран.


In [5]:
import torch


class NeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [[3.3, -38.]],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [176.],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 2:
            raise ValueError(
                f"Очікується 2 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою (float32 або float64)."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        return X @ self.W.T + self.b


In [6]:
model = NeuralNetwork(device="cuda")


In [7]:
tensor = torch.tensor([65.0,2.0], device='cuda')
tensor = tensor.reshape(1,2)
tensor.shape

torch.Size([1, 2])

In [8]:
model.predict(tensor)

tensor([[314.5000]], device='cuda:0', grad_fn=<AddBackward0>)

# **Завдання 6**

У таблиці наведено інформацію про три квартири.

| **Квартира** | **Площа (м²)** | **Кількість кімнат** |
| ------------ | -------------: | -------------------: |
| Квартира 1   |             40 |                    1 |
| Квартира 2   |             60 |                    3 |
| Квартира 3   |             100 |                    2 |

Виконайте наступні кроки:

1. Створіть **три окремі тензори** (`X1`, `X2`, `X3`), кожен з яких містить дані про одну квартиру.
2. За допомогою методу `predict()` обчисліть **прогнозовану ціну** для кожної квартири окремо.
3. Створіть **один тензор** `X` розміру **(3, 2)**, де:
   * кожен рядок відповідає одній квартирі;
   * перший стовпець — площа квартири;
   * другий стовпець — кількість кімнат.

4. За допомогою одного виклику `predict(X)` отримайте **прогнозовану ціну одразу для всіх трьох квартир**.
5. Виведіть розмір тензору з трьома прогнозованими цінами, який ви отримали на кроці 4.
6. Порівняйте результати, отримані окремими викликами `predict()` та одним спільним викликом `predict(X)`.


In [9]:
x1 = torch.tensor([40.0,1.0],device='cuda')
x2 = torch.tensor([60.0,3.0],device='cuda')
x3 = torch.tensor([100.0,2.0],device='cuda')

In [10]:
x1 = x1.reshape(1,2)
x2 = x2.reshape(1,2)
x3 = x3.reshape(1,2)

In [11]:
model.predict(x1)


tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [12]:
model.predict(x2)

tensor([[260.]], device='cuda:0', grad_fn=<AddBackward0>)

In [13]:
model.predict(x3)

tensor([[430.]], device='cuda:0', grad_fn=<AddBackward0>)

In [14]:
X = torch.tensor([[40.0,1.0],
     [60.0,3.0], 
     [100.0,2.0]], device='cuda')

In [15]:
y = model.predict(X)
y

tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)

# Завдання 7

Три квартири були продані, і стали відомі їхні **реальні ціни**.

| Квартира   | Реальна ціна (1000$) |
| ---------- | ---------------: |
| Квартира 1 |           210 |
| Квартира 2 |          310 |
| Квартира 3 |          360 |

Нехай прогноз моделі збережений у змінній `y_pred`, а реальні значення — у `y_true`.

Визначте, **наскільки модель помилилася**, використавши два різних підходи.

### Варіант 1

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Обчисліть середнє значення цієї різниці за допомогою `torch.mean()`.

### Варіант 2

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Позбудьтеся від'ємних значень за допомогою `torch.abs()`.
3. Обчисліть середнє значення отриманих помилок.

### Запитання

1. Який із двох варіантів краще характеризує якість моделі? Поясніть свою відповідь.
2. Напишіть функцію `loss_fn()`, яка реалізує обраний варіант.

```python
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    ...
```




In [16]:
def loss_fn(y_pred, y_true):
    mae = y_pred - y_true
    mae = mae.abs()
    mae = mae.mean()
    return mae
    

In [17]:
true = torch.tensor([[210.],[310.],[360.]],device='cuda')
print(loss_fn(y, true))

tensor(60., device='cuda:0', grad_fn=<MeanBackward0>)


# Завдання 8

У вашому розпорядженні є вчитель, який може навчити нейронну мережу робити точніші прогнози **цін на квартири**.

Клас `Teacher` вже реалізований. Під час створення об'єкта необхідно передати модель, яку потрібно навчати:

```python
teacher = Teacher(model)
```

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Виведіть тензор `X`, який містить дані про квартири:
   * площу квартири;
   * кількість кімнат.

3. Виведіть тензор `y_true` з **реальними цінами квартир**.
4. Отримайте прогноз моделі `y_pred`.
5. Виведіть прогнозовані ціни квартир.
6. За допомогою власної функції `loss_fn()` обчисліть помилку моделі.
7. Виведіть значення помилки.
8. Скористайтеся методом `teach()` класу `Teacher`, передавши йому обчислену помилку.
9. Після навчання знову отримайте прогноз `y_pred`.
10. Виведіть нові прогнозовані ціни квартир.
11. Знову обчисліть та виведіть помилку.
12. Зробіть висновок: **чи стала модель прогнозувати ціни квартир точніше після одного кроку навчання?**



In [18]:
import torch


class Teacher:
    def __init__(self, model, lr=0.02):
        """
        Створює вчителя для навчання моделі.

        Параметри:
            model (NeuralNetwork): модель, яку потрібно навчати.
            lr (float): швидкість навчання.
        """
        self.model = model

        self.optimizer = torch.optim.SGD(
            [model.W, model.b],
            lr=lr
        )

    def teach(self, loss):
        """
        Виконує один крок навчання.

        Параметри:
            loss (torch.Tensor): значення функції втрат.
        """
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()


In [19]:
teacher = Teacher(model)

In [20]:
X

tensor([[ 40.,   1.],
        [ 60.,   3.],
        [100.,   2.]], device='cuda:0')

In [28]:
y_true = torch.tensor([[210.],[310.],[360.]],device='cuda')
y_true

tensor([[210.],
        [310.],
        [360.]], device='cuda:0')

In [25]:
y_pred = model.predict(X)

In [26]:
y_pred

tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)

In [29]:
loss_before = loss_fn(y_pred, y_true)

In [30]:
teacher.teach(loss_before)

In [32]:
y_pred_after = model.predict(X)
y_pred_after

tensor([[248.6600],
        [227.9933],
        [376.6600]], device='cuda:0', grad_fn=<AddBackward0>)

In [33]:
loss_after = loss_fn(y_pred_after, y_true)
loss_after

tensor(45.7756, device='cuda:0', grad_fn=<MeanBackward0>)

# Завдання 9

Одного кроку навчання недостатньо, щоб модель навчилася добре прогнозувати ціни. Тому повторіть процес навчання **100 разів**.

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить дані про квартири.
3. Створіть тензор `y_true`, який містить реальні реальні ціни.
4. Створіть цикл, який виконається **100 разів**.
5. На кожній ітерації циклу:
   * отримайте прогноз моделі `y_pred`;
   * обчисліть помилку за допомогою функції `loss_fn()`;
   * виведіть помилку на екран;
   * передайте помилку в метод `teacher.teach()`, щоб виконати один крок навчання.
    
6. Після завершення циклу ще раз отримайте прогноз моделі.
7. Виведіть:
   * прогнозовані заробітні плати;
   * значення функції втрат.
    
8. Порівняйте отримані прогнози з реальними ціни. Зробіть висновок, чи покращилася точність моделі після 100 кроків навчання.
9. Cпробуйте зменшити навчальний крок в `teacher`

In [34]:
teacher = Teacher(model, lr=0.005)

In [37]:
for step in range(100):
    y_pred = model.predict(X)

    current_y_true = y_true.to(
        dtype=y_pred.dtype,
        device=y_pred.device
    ).reshape_as(y_pred)

    loss = loss_fn(y_pred, current_y_true)

    print(f"step: {step + 1}: loss = {loss.item():.4f}")

    teacher.teach(loss)

step: 1: loss = 45.7756
step: 2: loss = 42.2194
step: 3: loss = 45.3367
step: 4: loss = 43.9972
step: 5: loss = 42.6611
step: 6: loss = 45.7750
step: 7: loss = 42.2189
step: 8: loss = 45.3195
step: 9: loss = 43.9967
step: 10: loss = 42.6439
step: 11: loss = 45.7744
step: 12: loss = 42.2183
step: 13: loss = 45.3023
step: 14: loss = 43.9961
step: 15: loss = 42.6267
step: 16: loss = 45.7739
step: 17: loss = 42.2178
step: 18: loss = 45.2850
step: 19: loss = 43.9955
step: 20: loss = 42.6095
step: 21: loss = 45.7733
step: 22: loss = 42.2172
step: 23: loss = 45.2678
step: 24: loss = 43.9950
step: 25: loss = 42.5923
step: 26: loss = 45.7728
step: 27: loss = 42.2166
step: 28: loss = 45.2506
step: 29: loss = 43.9944
step: 30: loss = 42.5750
step: 31: loss = 45.7722
step: 32: loss = 42.2161
step: 33: loss = 45.2334
step: 34: loss = 43.9938
step: 35: loss = 42.5578
step: 36: loss = 45.7716
step: 37: loss = 42.2155
step: 38: loss = 45.2162
step: 39: loss = 43.9933
step: 40: loss = 42.5406
step: 41:

In [40]:
y_pred_final = model.predict(X)

In [42]:
y_true_final = torch.tensor([[210.],[310.],[360.]],device='cuda')

In [43]:
final_loss = loss_fn(y_pred_final, y_true_final)
final_loss

tensor(45.7643, device='cuda:0', grad_fn=<MeanBackward0>)

# Завдання 10

У вашому розпорядженні є нейронна мережа, яка прогнозує **ймовірність дощу**.

Модель використовує три ознаки:

* температура повітря (°C);
* вологість повітря (%);
* швидкість вітру (км/год).

Результатом роботи моделі є **два числа**:

1. ймовірність того, що **дощу не буде**;
2. ймовірність того, що **дощ буде**.

Скористайтеся методом `predict()`, щоб визначити ймовірності для таких погодних умов:

* температура — **20°C**;
* вологість — **80%**;
* швидкість вітру — **15 км/год**.



In [ ]:
import torch


class RainNeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [
                [0.03, 0.01, 0.02],
                [0.06, -0.01, 0.08]
            ],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [-0.2, -0.3],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 3:
            raise ValueError(
                f"Очікується 3 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        logits = X @ self.W.T + self.b
        return torch.softmax(logits, dim=1)

# Завдання 11

Метеостанція надала прогноз погоди на **4 дні**.

| День | Температура (°C) | Вологість (%) | Швидкість вітру (км/год) |
| ---- | ---------------: | ------------: | -----------------------: |
| 1    |               30 |            40 |                        5 |
| 2    |               22 |            85 |                       18 |
| 3    |               15 |            95 |                       25 |
| 4    |               28 |            60 |                       10 |

Виконайте наступні кроки:

1. Створіть один тензор `X` розміру **(4, 3)**, де кожен рядок містить дані про один день.

2. За допомогою методу `predict()` отримайте ймовірності для кожного дня `y_pred`.

3. Скористайтеся функцією `torch.argmax(..., dim=1)`, щоб визначити прогноз моделі `result`:

   * `0` — дощу не буде;
   * `1` — дощ буде.

4. Виведіть:

   * тензор із ймовірностями `y_pred`;
   * тензор із прогнозами `result`


# Завдання 12

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
| ---- | :-: |
| 1    |  Ні |
| 2    | Так |
| 3    | Так |
| 4    |  Ні |

Для навчання моделі використайте готову функцію втрат **CrossEntropyLoss** з бібліотеки **PyTorch**.

### Завдання

1. Створіть об'єкт функції втрат:

   ```python
   loss_fn = torch.nn.CrossEntropyLoss()
   ```

2. Створіть об'єкт класу `Teacher`, передавши йому модель.

3. Створіть тензор `X`, який містить погодні умови за всі 4 дні.

4. Створіть тензор `y_true`, який містить правильні відповіді:

   * `0` — дощу не було;
   * `1` — дощ був.

5. Створіть цикл, який виконається **100 разів**.

6. На кожній ітерації циклу:

   * отримайте ймовірності від моделі `y_pred`:
   * обчисліть помилку:
   * виведіть помилку
   * передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

7. Після завершення циклу ще раз отримайте прогноз моделі.

8. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:

   * `0` — дощу не буде;
   * `1` — дощ буде.

9. Виведіть:

   * ймовірності, отримані від моделі;
   * прогнози моделі (`0` або `1`);
   * правильні відповіді
   * значення функції втра


# Завдання 13

Попробуйте натренувати модель використовуючи функцію втрат, яку ви раніше застосовували для задачі визначення цін на квартири (`torch.nn.MSELoss()`), замість `CrossEntropyLoss`.

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
|------|-----|
| 1    | Ні  |
| 2    | Так |
| 3    | Так |
| 4    | Ні  |

**Завдання**

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить погодні умови за всі 4 дні.
3. Створіть тензор `y_true` розміром (4, 2), де кожен рядок містить інформацію про те чи йшов дощ в цей день:
   - `[1, 0]` — дощу не було
   - `[0, 1]` — дощ був
   -  формат інший тому що ваша функція вимагає щоб `y_true` та `y_pred` були однакового розміру
4. Створіть цикл, який виконається 100 разів.

На кожній ітерації циклу:
- отримайте ймовірності від моделі `y_pred`;
- обчисліть помилку;
- виведіть помилку;
- передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

6. Після завершення циклу ще раз отримайте прогноз моделі.
7. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:
   - 0 — дощу не буде;
   - 1 — дощ буде.

**Виведіть:**
- ймовірності, отримані від моделі;
- прогнози моделі (0 або 1);
- правильні відповіді;
- значення функції втрат.
